spring.application.name=tourplanner-backend
spring.docker.compose.file=compose.yaml

# Database
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/tourplanner}
spring.datasource.username=${DB_USERNAME:touruser}
spring.datasource.password=${DB_PASSWORD:secret}

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# OpenRoute
openroute.api.key = ${OPENROUTE_API_ah geKEY}